services:
  app:
    build: .
    container_name: image-app
    ports:
      - "8000:8000"
    volumes:
      - images_data:/app/images
      - logs_data:/app/logs
    networks:
      - app-network

volumes:
  images_data:
  logs_data:

networks:
  app-network:
    driver: bridge