services:
  app:
    build: .
    container_name: image-app
    volumes:
      - images_data:/app/images
      - logs_data:/app/logs:rw
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: image-nginx
    ports:
      - "8000:80"
    volumes:
      - images_data:/usr/share/nginx/html/images
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html/static
    depends_on:
      - app
    networks:
      - app-network

volumes:
  images_data:
  logs_data:

networks:
  app-network:
    driver: bridge